// frontend/components/sections/About.tsx
import Image from "next/image";
import FadeIn from "@/components/ui/FadeIn";
import SectionLabel from "@/components/ui/SectionLabel";

const stats = [
  { value: "2024", label: "Eröffnung" },
  { value: "30+", label: "Gerichte" },
  { value: "Täglich", label: "Frisch zubereitet" },
];

export default function About() {
  return (
    <section
      id="ueber-uns"
      className="relative py-24 lg:py-36 overflow-hidden"
      style={{ backgroundColor: "#131313" }}
    >
      {/* Subtle background texture */}
      <div
        className="absolute top-0 right-0 w-96 h-96 opacity-5 pointer-events-none"
        style={{
          background: "radial-gradient(circle, #f2ca50 0%, transparent 70%)",
          transform: "translate(30%, -30%)",
        }}
      />

      <div className="max-w-7xl mx-auto px-5 lg:px-10">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 lg:gap-24 items-center">
          {/* Text column */}
          <div>
            <FadeIn direction="left">
              <SectionLabel className="mb-6">Unsere Geschichte</SectionLabel>

              <h2
                className="mb-8 text-4xl lg:text-5xl"
                style={{ color: "#e5e2e1" }}
              >
                Ein Familienunternehmen.
                <br />
                <em
                  style={{
                    fontStyle: "italic",
                    color: "#f2ca50",
                  }}
                >
                  Eine Leidenschaft.
                </em>
              </h2>

              <div
                className="space-y-5 text-base leading-8"
                style={{ color: "#99907c" }}
              >
                <p>
                  Alles begann mit einem Lebensmittelgeschäft. Als Familie Moradi 2019 die Moradi
                  Lebensmittel KG in Urfahr eröffnete, war es mehr als nur ein Laden – es war ein
                  Stück Heimat mitten in Linz.
                </p>
                <p>
                  Im Juli 2024 folgte der nächste Schritt: Hamta Restaurant öffnete seine Türen
                  an der Urfahraner Hauptstraße. An jenem Ort, wo früher die Bar Cheers war, duftet
                  es heute nach frisch gegrilltem Lammfleisch, Safran und dem Brot des Morgenlandes.
                </p>
                <p>
                  Was uns antreibt? Der Respekt vor den Zutaten. Persische und afghane Küche lebt
                  von Geduld – lange gereifter Joghurt, handgemahlene Gewürze, Fleisch direkt vom
                  Vertrauenslieferanten. Kein Kompromiss. Nur echter Geschmack.
                </p>
              </div>

              {/* Quote */}
              <blockquote
                className="mt-10 pl-6 text-lg italic leading-relaxed"
                style={{
                  borderLeft: "2px solid #f2ca50",
                  color: "#c8c6c5",
                  fontFamily: "var(--font-serif)",
                }}
              >
                „Wir kochen so, wie unsere Mütter es uns beigebracht haben. Mit Zeit, mit Liebe
                und ohne Abkürzungen."
              </blockquote>
            </FadeIn>
          </div>

          {/* Image column */}
          <FadeIn direction="right" delay={150}>
            <div className="relative">
              {/* Main image */}
              <div
                className="relative overflow-hidden"
                style={{ borderRadius: "0.125rem", aspectRatio: "4/5" }}
              >
                <Image
                  src="/foods/food-5.jpg"
                  alt="Frisch gegrillte Spezialitäten im Hamta Restaurant"
                  fill
                  sizes="(max-width: 1024px) 100vw, 50vw"
                  className="object-cover"
                  style={{ filter: "brightness(0.9)" }}
                />
              </div>

              {/* Offset secondary image */}
              <div
                className="absolute -bottom-8 -left-8 w-48 h-48 lg:w-60 lg:h-60 overflow-hidden"
                style={{
                  borderRadius: "0.125rem",
                  border: "3px solid #131313",
                }}
              >
                <Image
                  src="/foods/food-8.jpg"
                  alt="Orientalische Gewürze und Zutaten"
                  fill
                  sizes="240px"
                  className="object-cover"
                />
              </div>

              {/* Gold accent */}
              <div
                className="absolute -top-4 -right-4 w-24 h-24"
                style={{
                  border: "1px solid rgba(242,202,80,0.25)",
                  borderRadius: "0.125rem",
                }}
              />
            </div>
          </FadeIn>
        </div>

        {/* Stats bar */}
        <FadeIn className="mt-20 lg:mt-28">
          <div
            className="grid grid-cols-3 py-10 lg:py-14"
            style={{
              backgroundColor: "#1e1e1e",
              borderRadius: "0.125rem",
            }}
          >
            {stats.map(({ value, label }, i) => (
              <div
                key={label}
                className="flex flex-col items-center text-center px-6"
                style={i > 0 ? { borderLeft: "1px solid rgba(255,255,255,0.06)" } : {}}
              >
                <span
                  className="text-3xl lg:text-4xl font-bold"
                  style={{
                    fontFamily: "var(--font-serif)",
                    background: "linear-gradient(135deg, #f2ca50, #d4af37)",
                    WebkitBackgroundClip: "text",
                    WebkitTextFillColor: "transparent",
                    backgroundClip: "text",
                  }}
                >
                  {value}
                </span>
                <span
                  className="mt-2 text-xs font-semibold uppercase tracking-widest"
                  style={{ color: "#4a4640", letterSpacing: "0.1em" }}
                >
                  {label}
                </span>
              </div>
            ))}
          </div>
        </FadeIn>
      </div>
    </section>
  );
}

// frontend/src/app/sections/about/about.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { FadeInDirective } from '../../shared/fade-in.directive';
import { ParallaxDirective } from '../../shared/parallax.directive';
import { SectionLabelComponent } from '../../shared/section-label/section-label.component';

@Component({
  selector: 'app-about',
  imports: [FadeInDirective, ParallaxDirective, SectionLabelComponent],
  templateUrl: './about.component.html',
  styleUrl: './about.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AboutComponent {
  readonly stats = [
    { value: '2026', label: 'Eröffnung' },
    { value: '20+', label: 'Italienische Klassiker' },
    { value: 'Neu', label: 'Frisch eröffnet in Urfahr' },
    { value: 'Zentral', label: 'Bushaltestelle direkt vor der Tür' },
  ];
}

<section id="ueber-uns" class="relative py-24 lg:py-36 overflow-hidden bg-[#151413]">
  <div class="absolute top-0 right-0 w-[34rem] h-[34rem] opacity-15 pointer-events-none [background:radial-gradient(circle,rgba(201,134,47,.38)_0%,transparent_70%)] translate-x-[35%] -translate-y-[35%]"></div>
  <div class="max-w-7xl mx-auto px-5 lg:px-10">
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-16 lg:gap-24 items-center">
      <div appFadeIn fadeDirection="left">
        <app-section-label class="block mb-6">Unsere Geschichte</app-section-label>
        <h2 class="mb-8 text-4xl lg:text-6xl text-[#eee7df]">Italienische Küche.<br/><em class="italic font-normal text-[#d89a4b]">Mitten in Urfahr.</em></h2>
        <div class="space-y-5 text-base leading-8 text-[#aaa199]">
          <p>Seit Juli 2026 ist Hamta ein Treffpunkt an der Urfahraner Hauptstraße. Der neue kulinarische Fokus bringt die entspannte Tischkultur Italiens nach Linz – modern interpretiert und ohne steife Regeln.</p>
          <p>Auf der Karte stehen vertraute Klassiker: Antipasti zum Teilen, Pasta mit klaren Aromen und Pizza aus heißem Ofen.</p>
          <p>Unser Anspruch bleibt bewusst einfach: sorgfältig ausgewählte Zutaten, Zeit in der Zubereitung und ein Service, bei dem man gerne noch ein wenig länger sitzen bleibt.</p>
        </div>
        <blockquote class="mt-10 pl-6 text-lg italic leading-relaxed border-l-2 border-[#c9862f] text-[#d8d0c8] font-serif">„Wenige gute Zutaten. Präzise zubereitet. Großzügig serviert.“</blockquote>
      </div>
      <div appFadeIn fadeDirection="right" [fadeDelay]="150">
        <div class="relative overflow-hidden rounded-sm border border-[rgba(201,134,47,.2)] aspect-[4/5] shadow-[0_30px_80px_rgba(0,0,0,.34)]">
          <div appParallax [parallaxSpeed]="0.09" class="absolute -inset-y-[12%] inset-x-0 will-change-transform">
            <img src="/assets/food-9.jpg" alt="Kreativ angerichtete Vorspeise im Hamta Restaurant" loading="lazy" class="h-full w-full object-cover brightness-[.78]" />
          </div>
          <div class="absolute inset-0 [background:linear-gradient(to_top,rgba(14,14,14,.8)_0%,transparent_55%)]"></div>
          <div class="glass-gold absolute bottom-5 left-5 right-5 p-5 sm:left-7 sm:right-auto sm:max-w-xs">
            <span class="section-label">La tavola</span>
            <p class="mt-2 text-lg font-serif italic text-[#eee7df]">Gute Abende beginnen am Tisch.</p>
          </div>
        </div>
      </div>
    </div>
    <div appFadeIn class="mt-20 lg:mt-28">
      <div class="glass-gold grid grid-cols-2 lg:grid-cols-4 gap-y-10 py-10 lg:py-14 rounded-sm">
        @for (stat of stats; track stat.label; let i = $index) {
          <div class="flex flex-col items-center text-center px-2 sm:px-6" [class.border-l]="i % 2 === 1" [class.lg:border-l]="i > 0" [class.border-white/6]="i > 0">
            <span class="text-2xl sm:text-3xl lg:text-4xl font-bold font-serif text-gold-gradient">{{ stat.value }}</span>
            <span class="mt-2 text-[9px] sm:text-xs font-semibold uppercase tracking-wider text-[#aaa199] sm:tracking-widest">{{ stat.label }}</span>
          </div>
        }
      </div>
    </div>
  </div>
</section>
