// frontend-legacy/src/app/sections/hero/hero.component.ts
import { DOCUMENT, isPlatformBrowser } from '@angular/common';
import { ChangeDetectionStrategy, Component, inject, PLATFORM_ID } from '@angular/core';
import { LucideChevronDown, LucidePhone, LucideUtensilsCrossed } from '@lucide/angular';

@Component({
  selector: 'app-hero',
  imports: [LucideChevronDown, LucidePhone, LucideUtensilsCrossed],
  templateUrl: './hero.component.html',
  styleUrl: './hero.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class HeroComponent {
  private readonly document = inject(DOCUMENT);
  private readonly isBrowser = isPlatformBrowser(inject(PLATFORM_ID));

  scrollTo(id: string): void {
    if (this.isBrowser) this.document.getElementById(id)?.scrollIntoView({ behavior: 'smooth' });
  }
}

<section id="start" class="relative min-h-screen flex flex-col justify-center overflow-hidden">
  <div class="absolute inset-0 z-0">
    <img src="/foods/food-1.jpg" alt="Hamta Restaurant – Persische Küche in Linz" fetchpriority="high" class="absolute inset-0 w-full h-full object-cover object-center brightness-[.45]" />
    <div class="absolute inset-0 [background:linear-gradient(to_bottom,rgba(19,19,19,.35)_0%,rgba(19,19,19,.55)_40%,rgba(19,19,19,.88)_75%,#131313_100%)]"></div>
    <div class="absolute inset-0 [background:linear-gradient(to_right,rgba(19,19,19,.6)_0%,transparent_60%)]"></div>
  </div>
  <div class="relative z-10 max-w-7xl mx-auto px-5 lg:px-10 w-full pt-24 pb-32 lg:pt-32 lg:pb-40">
    <div class="max-w-2xl">
      <div class="hero-animate hero-delay-1 flex items-center gap-3 mb-7"><span class="section-label">Persische &amp; Afghane Küche · Linz · Urfahr</span></div>
      <h1 class="hero-animate hero-delay-2 font-serif text-[#e5e2e1] font-bold leading-none [font-size:clamp(3rem,8vw,6rem)] [letter-spacing:-.03em]">Hamta<br/><em class="italic text-gold-gradient">Restaurant</em></h1>
      <p class="hero-animate hero-delay-3 mt-6 text-lg lg:text-xl leading-relaxed text-[#c8c6c5] font-normal max-w-[480px]">Echt. Handgemacht. Täglich frisch aus Urfahr.</p>
      <p class="hero-animate hero-delay-4 mt-3 text-sm lg:text-base leading-relaxed text-[#99907c] max-w-[420px]">Der Geschmack Persiens und Afghanistans – seit Juli 2024 mitten in Linz.</p>
      <div class="hero-animate hero-delay-5 flex flex-wrap gap-4 mt-10">
        <button type="button" (click)="scrollTo('menu')" class="btn-gold"><svg lucideUtensilsCrossed [size]="14" [strokeWidth]="2.5"></svg>Speisekarte ansehen</button>
        <a href="tel:+43732000000" class="btn-outline"><svg lucidePhone [size]="14" [strokeWidth]="2.5"></svg>Anrufen</a>
      </div>
      <div class="hero-animate hero-delay-6 flex flex-wrap gap-6 mt-12">
        <div><div class="section-label mb-1">Öffnungszeiten</div><div class="text-sm text-[#c8c6c5]">Di – So &nbsp; 11:00 – 22:00</div></div>
        <div class="w-px self-stretch bg-white/8"></div>
        <div><div class="section-label mb-1">Adresse</div><div class="text-sm text-[#c8c6c5]">Hauptstraße 42, 4040 Linz</div></div>
        <div class="w-px self-stretch bg-white/8"></div>
        <div><div class="section-label mb-1">Lieferservice</div><div class="text-sm text-[#c8c6c5]">Verfügbar</div></div>
      </div>
    </div>
  </div>
  <button type="button" (click)="scrollTo('ueber-uns')" class="absolute bottom-8 left-1/2 -translate-x-1/2 z-10 flex flex-col items-center gap-2 animate-scroll-bounce" aria-label="Nach unten scrollen"><span class="text-[10px] font-semibold uppercase tracking-widest text-[#4a4640]">Entdecken</span><svg lucideChevronDown [size]="18" [strokeWidth]="1.5" class="text-[#4a4640]"></svg></button>
</section>

// frontend-legacy/components/sections/Hero.tsx
"use client";

import Image from "next/image";
import { ChevronDown, Phone, UtensilsCrossed } from "lucide-react";

export default function Hero() {
  const scrollToMenu = () => {
    document.getElementById("menu")?.scrollIntoView({ behavior: "smooth" });
  };

  const scrollDown = () => {
    document.getElementById("ueber-uns")?.scrollIntoView({ behavior: "smooth" });
  };

  return (
    <section
      id="start"
      className="relative min-h-screen flex flex-col justify-center overflow-hidden"
    >
      {/* Background image */}
      <div className="absolute inset-0 z-0">
        <Image
          src="/foods/food-1.jpg"
          alt="Hamta Restaurant – Persische Küche in Linz"
          fill
          priority
          quality={90}
          sizes="100vw"
          className="object-cover object-center"
          style={{ filter: "brightness(0.45)" }}
        />
        {/* Gradient overlay */}
        <div
          className="absolute inset-0"
          style={{
            background:
              "linear-gradient(to bottom, rgba(19,19,19,0.35) 0%, rgba(19,19,19,0.55) 40%, rgba(19,19,19,0.88) 75%, #131313 100%)",
          }}
        />
        {/* Subtle left vignette */}
        <div
          className="absolute inset-0"
          style={{
            background:
              "linear-gradient(to right, rgba(19,19,19,0.6) 0%, transparent 60%)",
          }}
        />
      </div>

      {/* Content */}
      <div className="relative z-10 max-w-7xl mx-auto px-5 lg:px-10 w-full pt-24 pb-32 lg:pt-32 lg:pb-40">
        <div className="max-w-2xl">
          {/* Label */}
          <div
            className="flex items-center gap-3 mb-7 opacity-0"
            style={{ animation: "fadeInUp 0.6s ease 0.2s forwards" }}
          >
            <span className="section-label">Persische &amp; Afghane Küche · Linz · Urfahr</span>
          </div>

          {/* Headline */}
          <h1
            className="opacity-0"
            style={{
              fontFamily: "var(--font-serif)",
              fontSize: "clamp(3rem, 8vw, 6rem)",
              fontWeight: 700,
              color: "#e5e2e1",
              lineHeight: 1.0,
              letterSpacing: "-0.03em",
              animation: "fadeInUp 0.7s ease 0.35s forwards",
            }}
          >
            Hamta
            <br />
            <em
              style={{
                fontStyle: "italic",
                background: "linear-gradient(135deg, #f2ca50, #d4af37)",
                WebkitBackgroundClip: "text",
                WebkitTextFillColor: "transparent",
                backgroundClip: "text",
              }}
            >
              Restaurant
            </em>
          </h1>

          {/* Tagline */}
          <p
            className="mt-6 text-lg lg:text-xl leading-relaxed opacity-0"
            style={{
              color: "#c8c6c5",
              fontWeight: 400,
              maxWidth: "480px",
              animation: "fadeInUp 0.7s ease 0.5s forwards",
            }}
          >
            Echt. Handgemacht. Täglich frisch aus Urfahr.
          </p>
          <p
            className="mt-3 text-sm lg:text-base leading-relaxed opacity-0"
            style={{
              color: "#99907c",
              maxWidth: "420px",
              animation: "fadeInUp 0.7s ease 0.62s forwards",
            }}
          >
            Der Geschmack Persiens und Afghanistans – seit Juli 2024 mitten in Linz.
          </p>

          {/* CTAs */}
          <div
            className="flex flex-wrap gap-4 mt-10 opacity-0"
            style={{ animation: "fadeInUp 0.7s ease 0.75s forwards" }}
          >
            <button onClick={scrollToMenu} className="btn-gold">
              <UtensilsCrossed size={14} strokeWidth={2.5} />
              Speisekarte ansehen
            </button>
            <a href="tel:+43732000000" className="btn-outline">
              <Phone size={14} strokeWidth={2.5} />
              Anrufen
            </a>
          </div>

          {/* Info strip */}
          <div
            className="flex flex-wrap gap-6 mt-12 opacity-0"
            style={{ animation: "fadeInUp 0.7s ease 0.9s forwards" }}
          >
            <div>
              <div className="section-label mb-1">Öffnungszeiten</div>
              <div className="text-sm" style={{ color: "#c8c6c5" }}>
                Di – So &nbsp; 11:00 – 22:00
              </div>
            </div>
            <div
              className="w-px self-stretch"
              style={{ background: "rgba(255,255,255,0.08)" }}
            />
            <div>
              <div className="section-label mb-1">Adresse</div>
              <div className="text-sm" style={{ color: "#c8c6c5" }}>
                Hauptstraße 42, 4040 Linz
              </div>
            </div>
            <div
              className="w-px self-stretch"
              style={{ background: "rgba(255,255,255,0.08)" }}
            />
            <div>
              <div className="section-label mb-1">Lieferservice</div>
              <div className="text-sm" style={{ color: "#c8c6c5" }}>
                Verfügbar
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Scroll indicator */}
      <button
        onClick={scrollDown}
        className="absolute bottom-8 left-1/2 -translate-x-1/2 z-10 flex flex-col items-center gap-2 animate-scroll-bounce"
        aria-label="Nach unten scrollen"
      >
        <span
          className="text-[10px] font-semibold uppercase tracking-widest"
          style={{ color: "#4a4640" }}
        >
          Entdecken
        </span>
        <ChevronDown size={18} style={{ color: "#4a4640" }} strokeWidth={1.5} />
      </button>
    </section>
  );
}
