// frontend-legacy/components/layout/Footer.tsx
"use client";

import Image from "next/image";
import Link from "next/link";
import { MapPin, Clock, Phone } from "lucide-react";

function InstagramIcon({ size = 14 }: { size?: number }) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect x="2" y="2" width="20" height="20" rx="5" ry="5" />
      <circle cx="12" cy="12" r="4" />
      <circle cx="17.5" cy="6.5" r="1" fill="currentColor" stroke="none" />
    </svg>
  );
}

const navLinks = [
  { label: "Start", href: "#start" },
  { label: "Über uns", href: "#ueber-uns" },
  { label: "Speisekarte", href: "#menu" },
  { label: "Galerie", href: "#galerie" },
  { label: "Kontakt", href: "#kontakt" },
];

const hours = [
  { day: "Montag", time: "Ruhetag", closed: true },
  { day: "Dienstag – Sonntag", time: "11:00 – 22:00", closed: false },
];

export default function Footer() {
  return (
    <footer
      style={{
        backgroundColor: "#0e0e0e",
        borderTop: "1px solid rgba(242,202,80,0.12)",
      }}
    >
      <div className="max-w-7xl mx-auto px-5 lg:px-10 py-16 lg:py-20">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-10 lg:gap-12">
          {/* Brand */}
          <div className="lg:col-span-1">
            <div className="flex items-center gap-3 mb-5">
              <div className="relative w-8 h-11">
                <Image
                  src="/logo.png"
                  alt="Hamta Restaurant"
                  fill
                  sizes="32px"
                  className="object-contain"
                />
              </div>
              <span
                className="text-sm font-semibold tracking-widest uppercase"
                style={{ color: "#e5e2e1", letterSpacing: "0.12em" }}
              >
                Hamta
              </span>
            </div>
            <p className="text-sm leading-relaxed mb-6" style={{ color: "#4a4640" }}>
              Persische und afghane Küche in Linz-Urfahr. Täglich frisch zubereitet mit Zutaten aus eigenem Handel.
            </p>
            <a
              href="https://www.instagram.com/hamtarestaurant1/"
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-2 text-xs font-semibold uppercase tracking-widest transition-colors duration-150"
              style={{ color: "#99907c", letterSpacing: "0.1em" }}
              onMouseEnter={(e) => (e.currentTarget.style.color = "#f2ca50")}
              onMouseLeave={(e) => (e.currentTarget.style.color = "#99907c")}
            >
              <InstagramIcon size={14} />
              @hamtarestaurant1
            </a>
          </div>

          {/* Navigation */}
          <div>
            <h3
              className="text-xs font-semibold uppercase tracking-widest mb-5"
              style={{ color: "#f2ca50", letterSpacing: "0.12em" }}
            >
              Navigation
            </h3>
            <ul className="flex flex-col gap-3">
              {navLinks.map((link) => (
                <li key={link.href}>
                  <Link
                    href={link.href}
                    className="text-sm transition-colors duration-150"
                    style={{ color: "#4a4640" }}
                    onMouseEnter={(e) => (e.currentTarget.style.color = "#e5e2e1")}
                    onMouseLeave={(e) => (e.currentTarget.style.color = "#4a4640")}
                  >
                    {link.label}
                  </Link>
                </li>
              ))}
            </ul>
          </div>

          {/* Hours */}
          <div>
            <h3
              className="text-xs font-semibold uppercase tracking-widest mb-5"
              style={{ color: "#f2ca50", letterSpacing: "0.12em" }}
            >
              Öffnungszeiten
            </h3>
            <ul className="flex flex-col gap-3">
              {hours.map(({ day, time, closed }) => (
                <li key={day} className="flex items-start justify-between gap-4 text-sm">
                  <span style={{ color: "#4a4640" }}>{day}</span>
                  <span
                    style={{ color: closed ? "#4a4640" : "#99907c" }}
                    className="whitespace-nowrap"
                  >
                    {time}
                  </span>
                </li>
              ))}
            </ul>
            <div
              className="flex items-start gap-2 mt-5 text-sm"
              style={{ color: "#4a4640" }}
            >
              <Clock size={13} className="mt-0.5 shrink-0" />
              <span>Lieferservice verfügbar</span>
            </div>
          </div>

          {/* Contact */}
          <div>
            <h3
              className="text-xs font-semibold uppercase tracking-widest mb-5"
              style={{ color: "#f2ca50", letterSpacing: "0.12em" }}
            >
              Adresse
            </h3>
            <address className="not-italic flex flex-col gap-3">
              <a
                href="https://maps.google.com/?q=Hauptstraße+42,+4040+Linz"
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-start gap-2 text-sm transition-colors duration-150"
                style={{ color: "#4a4640" }}
                onMouseEnter={(e) => (e.currentTarget.style.color = "#99907c")}
                onMouseLeave={(e) => (e.currentTarget.style.color = "#4a4640")}
              >
                <MapPin size={13} className="mt-0.5 shrink-0" />
                <span>Hauptstraße 42<br />4040 Linz (Urfahr)</span>
              </a>
              <a
                href="tel:+43732000000"
                className="flex items-center gap-2 text-sm transition-colors duration-150"
                style={{ color: "#4a4640" }}
                onMouseEnter={(e) => (e.currentTarget.style.color = "#f2ca50")}
                onMouseLeave={(e) => (e.currentTarget.style.color = "#4a4640")}
              >
                <Phone size={13} />
                Jetzt anrufen
              </a>
            </address>
          </div>
        </div>

        {/* Bottom bar */}
        <div
          className="mt-14 pt-6 flex flex-col sm:flex-row items-center justify-between gap-3 text-xs"
          style={{
            borderTop: "1px solid rgba(255,255,255,0.05)",
            color: "#353535",
          }}
        >
          <span>© {new Date().getFullYear()} Hamta Restaurant. Alle Rechte vorbehalten.</span>
          <div className="flex items-center gap-5">
            <Link
              href="/impressum"
              style={{ color: "#353535" }}
              onMouseEnter={(e) => (e.currentTarget.style.color = "#99907c")}
              onMouseLeave={(e) => (e.currentTarget.style.color = "#353535")}
            >
              Impressum
            </Link>
            <Link
              href="/datenschutz"
              style={{ color: "#353535" }}
              onMouseEnter={(e) => (e.currentTarget.style.color = "#99907c")}
              onMouseLeave={(e) => (e.currentTarget.style.color = "#353535")}
            >
              Datenschutz
            </Link>
          </div>
        </div>
      </div>
    </footer>
  );
}

// frontend/src/app/layout/footer/footer.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { LucideClock, LucideMapPin, LucidePhone } from '@lucide/angular';

@Component({
  selector: 'app-footer',
  imports: [RouterLink, LucideClock, LucideMapPin, LucidePhone],
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FooterComponent {
  readonly year = new Date().getFullYear();
  readonly navLinks = [
    { label: 'Start', href: '#start' }, { label: 'Über uns', href: '#ueber-uns' },
    { label: 'Speisekarte', href: '#menu' }, { label: 'Galerie', href: '#galerie' },
    { label: 'Kontakt', href: '#kontakt' },
  ];
}

<footer class="bg-[#0e0e0e] border-t border-[rgba(242,202,80,.12)]">
  <div class="max-w-7xl mx-auto px-5 lg:px-10 py-16 lg:py-20">
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-10 lg:gap-12">
      <div>
        <div class="flex items-center gap-3 mb-5"><div class="relative w-8 h-11"><img src="/logo.png" alt="Hamta Restaurant" class="absolute inset-0 w-full h-full object-contain" /></div><span class="text-sm font-semibold tracking-widest uppercase text-[#e5e2e1] [letter-spacing:.12em]">Hamta</span></div>
        <p class="text-sm leading-relaxed mb-6 text-[#4a4640]">Persische und afghane Küche in Linz-Urfahr. Täglich frisch zubereitet mit Zutaten aus eigenem Handel.</p>
        <a href="https://www.instagram.com/hamtarestaurant1/" target="_blank" rel="noopener noreferrer" class="flex items-center gap-2 text-xs font-semibold uppercase tracking-widest text-[#99907c] hover:text-[#f2ca50] transition-colors duration-150 [letter-spacing:.1em]">
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="2" width="20" height="20" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" fill="currentColor" stroke="none"/></svg>@hamtarestaurant1
        </a>
      </div>
      <div>
        <h3 class="footer-heading">Navigation</h3>
        <ul class="flex flex-col gap-3">@for (link of navLinks; track link.href) { <li><a [href]="link.href" class="text-sm text-[#4a4640] hover:text-[#e5e2e1] transition-colors duration-150">{{ link.label }}</a></li> }</ul>
      </div>
      <div>
        <h3 class="footer-heading">Öffnungszeiten</h3>
        <ul class="flex flex-col gap-3 text-sm"><li class="flex justify-between gap-4"><span class="text-[#4a4640]">Montag</span><span class="text-[#4a4640] whitespace-nowrap">Ruhetag</span></li><li class="flex justify-between gap-4"><span class="text-[#4a4640]">Dienstag – Sonntag</span><span class="text-[#99907c] whitespace-nowrap">11:00 – 22:00</span></li></ul>
        <div class="flex items-start gap-2 mt-5 text-sm text-[#4a4640]"><svg lucideClock [size]="13" class="mt-0.5 shrink-0"></svg><span>Lieferservice verfügbar</span></div>
      </div>
      <div>
        <h3 class="footer-heading">Adresse</h3>
        <address class="not-italic flex flex-col gap-3">
          <a href="https://maps.google.com/?q=Hauptstraße+42,+4040+Linz" target="_blank" rel="noopener noreferrer" class="flex items-start gap-2 text-sm text-[#4a4640] hover:text-[#99907c] transition-colors duration-150"><svg lucideMapPin [size]="13" class="mt-0.5 shrink-0"></svg><span>Hauptstraße 42<br/>4040 Linz (Urfahr)</span></a>
          <a href="tel:+43732000000" class="flex items-center gap-2 text-sm text-[#4a4640] hover:text-[#f2ca50] transition-colors duration-150"><svg lucidePhone [size]="13"></svg>Jetzt anrufen</a>
        </address>
      </div>
    </div>
    <div class="mt-14 pt-6 flex flex-col sm:flex-row items-center justify-between gap-3 text-xs border-t border-white/5 text-[#353535]">
      <span>© {{ year }} Hamta Restaurant. Alle Rechte vorbehalten.</span>
      <div class="flex items-center gap-5"><a routerLink="/impressum" class="hover:text-[#99907c]">Impressum</a><a routerLink="/datenschutz" class="hover:text-[#99907c]">Datenschutz</a></div>
    </div>
  </div>
</footer>
