// frontend-legacy/components/layout/LegalPageHeader.tsx
"use client";

import Link from "next/link";

export default function LegalPageHeader() {
  return (
    <div
      className="sticky top-0 z-50 flex items-center justify-between px-5 lg:px-10 h-14 border-b"
      style={{
        backgroundColor: "#131313",
        borderColor: "rgba(242,202,80,0.10)",
      }}
    >
      <Link
        href="/"
        className="text-xs font-semibold uppercase tracking-widest transition-colors duration-150"
        style={{ color: "#99907c", letterSpacing: "0.12em" }}
        onMouseEnter={(e) => (e.currentTarget.style.color = "#f2ca50")}
        onMouseLeave={(e) => (e.currentTarget.style.color = "#99907c")}
      >
        ← Zurück
      </Link>
      <span
        className="text-xs font-semibold uppercase tracking-widest"
        style={{ color: "#353535", letterSpacing: "0.12em" }}
      >
        Hamta Restaurant
      </span>
    </div>
  );
}

// frontend-legacy/src/app/layout/legal-page-header/legal-page-header.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-legal-page-header',
  imports: [RouterLink],
  templateUrl: './legal-page-header.component.html',
  styleUrl: './legal-page-header.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LegalPageHeaderComponent {}

<header
  class="sticky top-0 z-50 flex items-center justify-between px-5 lg:px-10 h-14 border-b border-white/5 bg-[rgba(14,14,14,.96)] backdrop-blur-xl"
>
  <a
    routerLink="/"
    class="text-xs font-semibold uppercase tracking-widest text-[#99907c] hover:text-[#f2ca50] transition-colors duration-150"
  >
    ← Zurück zur Startseite
  </a>
  <span class="text-xs font-semibold uppercase tracking-widest text-[#f2ca50]">Hamta</span>
</header>
