// frontend/src/app/layout/mobile-nav/mobile-nav.component.ts
import { isPlatformBrowser } from '@angular/common';
import { afterNextRender, ChangeDetectionStrategy, Component, inject, OnDestroy, PLATFORM_ID, signal } from '@angular/core';
import { LucideHome, LucideMapPin, LucidePhone, LucideUtensilsCrossed } from '@lucide/angular';

@Component({
  selector: 'app-mobile-nav',
  imports: [LucideHome, LucideMapPin, LucidePhone, LucideUtensilsCrossed],
  templateUrl: './mobile-nav.component.html',
  styleUrl: './mobile-nav.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class MobileNavComponent implements OnDestroy {
  readonly active = signal('#start');
  private observer?: IntersectionObserver;

  constructor() {
    if (!isPlatformBrowser(inject(PLATFORM_ID))) return;
    afterNextRender(() => {
      this.observer = new IntersectionObserver(
        (entries) => entries.forEach((entry) => entry.isIntersecting && this.active.set(`#${entry.target.id}`)),
        { threshold: 0.3 },
      );
      ['start', 'ueber-uns', 'menu', 'galerie', 'kontakt'].forEach((id) => {
        const element = document.getElementById(id);
        if (element) this.observer?.observe(element);
      });
    });
  }

  ngOnDestroy(): void { this.observer?.disconnect(); }
}

<nav
  class="mobile-nav-glass fixed bottom-0 left-0 right-0 z-50 lg:hidden"
  aria-label="Schnellnavigation"
>
  <div class="flex items-stretch [padding-bottom:env(safe-area-inset-bottom)]">
    <a
      href="#start"
      [class.text-[#d89a4b]]="active() === '#start'"
      [class.text-[#aaa199]]="active() !== '#start'"
      class="mobile-nav-item"
    >
      <svg lucideHome [size]="20" [strokeWidth]="1.8"></svg>
      <span>Start</span>
    </a>
    <a
      href="#menu"
      [class.text-[#d89a4b]]="active() === '#menu'"
      [class.text-[#aaa199]]="active() !== '#menu'"
      class="mobile-nav-item"
    >
      <svg lucideUtensilsCrossed [size]="20" [strokeWidth]="1.8"></svg>
      <span>Speisekarte</span>
    </a>
    <a href="tel:+43732000000" class="mobile-nav-item text-[#d89a4b]">
      <svg lucidePhone [size]="20" [strokeWidth]="1.8"></svg>
      <span>Anrufen</span>
    </a>
    <a
      href="#kontakt"
      [class.text-[#d89a4b]]="active() === '#kontakt'"
      [class.text-[#aaa199]]="active() !== '#kontakt'"
      class="mobile-nav-item"
    >
      <svg lucideMapPin [size]="20" [strokeWidth]="1.8"></svg>
      <span>Standort</span>
    </a>
  </div>
</nav>

// frontend/components/layout/MobileNav.tsx
"use client";

import Link from "next/link";
import { Home, UtensilsCrossed, Phone, MapPin } from "lucide-react";
import { useEffect, useState } from "react";

const items = [
  { label: "Start", href: "#start", icon: Home },
  { label: "Speisekarte", href: "#menu", icon: UtensilsCrossed },
  { label: "Anrufen", href: "tel:+43732000000", icon: Phone, isPhone: true },
  { label: "Standort", href: "#kontakt", icon: MapPin },
];

export default function MobileNav() {
  const [active, setActive] = useState("#start");

  useEffect(() => {
    const sections = ["start", "ueber-uns", "menu", "galerie", "kontakt"];
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            setActive(`#${entry.target.id}`);
          }
        });
      },
      { threshold: 0.3 }
    );
    sections.forEach((id) => {
      const el = document.getElementById(id);
      if (el) observer.observe(el);
    });
    return () => observer.disconnect();
  }, []);

  return (
    <nav
      className="fixed bottom-0 left-0 right-0 z-50 lg:hidden"
      style={{
        backgroundColor: "#1e1e1e",
        borderTop: "1px solid rgba(255,255,255,0.06)",
      }}
    >
      <div className="flex items-stretch" style={{ paddingBottom: "env(safe-area-inset-bottom)" }}>
        {items.map(({ label, href, icon: Icon, isPhone }) => {
          const isActive = !isPhone && active === href;
          return isPhone ? (
            <a
              key={href}
              href={href}
              className="flex flex-col items-center justify-center flex-1 py-3 gap-1 transition-colors duration-150"
              style={{ color: "#f2ca50" }}
            >
              <Icon size={20} strokeWidth={1.8} />
              <span className="text-[10px] font-semibold tracking-wide uppercase">{label}</span>
            </a>
          ) : (
            <Link
              key={href}
              href={href}
              className="flex flex-col items-center justify-center flex-1 py-3 gap-1 transition-colors duration-150"
              style={{ color: isActive ? "#f2ca50" : "#99907c" }}
            >
              <Icon size={20} strokeWidth={1.8} />
              <span className="text-[10px] font-semibold tracking-wide uppercase">{label}</span>
            </Link>
          );
        })}
      </div>
    </nav>
  );
}
